/**
 * RichTable Sample
 * © 2014 Force.com Developer
 * ----------------------------------------
 * @createdName      : Taiki,Yoshikawa
 * @lastModifiedName : Taiki,Yoshikawa
 * ----------------------------------------
 */
@isTest
private class RichTableSampleControllerTest {
    
    /**
      * RichTableSampleControllerTest
      */
    static testMethod void RichTableSampleControllerTest() {
        
        Test.startTest();
        
        RichTableSampleController cls = new RichTableSampleController();
        
        Test.stopTest();
    }
}